### ISSUE TITLE
Package libpcl for Windows

### ISSUE THREAD

**Issue by clalancette** [ros2/choco-packages#1]
In order for ros2/pcl_conversions#1 to work on Windows, we'll need to have PCL packaged.  This isn't an urgent need right now, as the current demo only needs to work on Linux.  However, I believe pcl_conversions is core enough to perception that we are eventually going to want to have it working on Windows.  There is some information about downloading the pre-built binaries, and building from source, here: http://pointclouds.org/downloads/windows.html

**Comment by traversaro** [comment]
If any random users stumbles on this issue from a Google search, it may be useful to add the pointer that PCL is currently available as a Chocolatey package in the ROS1 distribution on Chocolatey, see: 
* https://ros-win.visualstudio.com/ros-win/_git/rosdep-au-packages?path=%2Flibpcl&version=GBmaster
* https://roswin.azurewebsites.net/packages/libpcl/

**Comment by nuclearsandwich** [comment]
Thanks for that info @traversaro! 

In the future we'll be looking at sharing some of these foundational dependencies between ROS 1 and ROS 2 on Windows. That combined with the fact that there's no immediate need for this on Windows has me thinking we ought to close this particular issue.

**Comment by jackjansen** [comment]
@traversaro thank you for that google fodder. I was happy I found it, but unfortunately the package URL doesn't work anymore: `roswin.azurewebsites.net` no longer exists...

**Comment by traversaro** [comment]
> 
> 
> @traversaro thank you for that google fodder. I was happy I found it, but unfortunately the package URL doesn't work anymore: `roswin.azurewebsites.net` no longer exists...

The Choco repo for the ROSOnWindows (looking in http://wiki.ros.org/Installation/Windows) seems now to be https://aka.ms/ros/public , but I could not find any more the nice public-facing website, perhaps @seanyen may know something more.

However, just FYI PCL is available on Windows also on vcpkg ( https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160, pcl port) or conda-forge (https://anaconda.org/conda-forge/pcl).
