### ISSUE TITLE
tinyxml12 not installed. The package was not found with the source(s) listed.

### ISSUE THREAD

**Issue by kevinlinxc** [ros2/choco-packages#20]
I downloaded all the packages from this repo for ROS2, and all of them installed correctly using choco except for tinyxml12. Here is the error:

![image](https://user-images.githubusercontent.com/44324811/213887078-8566c20e-41ee-43ed-93ef-de2c1da0fb2d.png)

Small note, I am trying to set up ROS2 on Windows 11, which some people say they've been able to do.

**Comment by arjo129** [comment]
Did you mean TinyXML2? I don't see any TinyXML12 as dependency.

**Comment by kevinlinxc** [comment]
My bad, I must have been hallucinating or it was a typo that was fixed
